/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package belajar.coroutine.app

import belajar.coroutine.utilities.StringUtils

import org.apache.commons.text.WordUtils
import java.util.*

fun main() {
    val tokens = StringUtils.split(MessageUtils.getMessage())
    val result = StringUtils.join(tokens)
//    println(WordUtils.capitalize(result))

    val runnable = Runnable {
        println(Date())
        Thread.sleep(2_000)
        println("Hello world")
    }

    val thread = Thread(runnable)
    thread.start()
    Thread.sleep(3_000)
    println(Date())

}
